apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7zesOf2KejKLO1TYPYrOGjO8cAs7tW0N0pw=,iv:MLhV/bddqH73cuvvBrse6TF0r5jXMvIn0dKCenLTYzg=,tag:B8b28FEPD5V960kgaLFNlA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:vlP1fxJRQjUMcaAZf+xxpxD7GK6nJFPiktPwodeRWCZq7kkDvQ==,iv:UZpwZZUnrYvwaD/N+naHLU8r1mYjCXY/TQKylIIfixc=,tag:78n0ZJKTJ9sm86su6JLm3g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:8JC3XQ9zEIfKQU437HspK4I=,iv:bArRdEyMCtieOD3qg/cH8DKX5USelUlQlBLObybqxzw=,tag:AMcSkoMkjjOIYU5Pl1IukA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVStkT05ac1ErNzNDZGZW
            eG5ka2hCZnRkNXNhODFmVlYrRkV2TWwveW5BCmJJbXczUmtHTFVOekJPR0xTOUVr
            UTlFUkJWcWJxSFNpM1R4R2pWSi9xd1EKLS0tIDdiWlpNdG95cnJhKzR3TWYwM3Bh
            WWNpMEdQMHMvSTJ4REJMYXAvZVMydjgK40rSXHFt88/u12R7jk/MaM7KRJTLb+X3
            AiUXNNnFi9WSjF5NuI/fEoFHxZFkeeVp54hk/Ukd4YBDrORNKvmN0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T20:24:11Z"
    mac: ENC[AES256_GCM,data:M00n1WJpac12k0u2tKlqKG8FUs4ZbIqzl0hcdzbr+wryQj7iGLV+eNlyZ5gXJtkqs2NV55H14SOR6sKnivhwwh/FGC3aR/JhGPMHHTdOq5S5bi1gp4HnzzA6q2HtpjDc1CAHCQnppj69wdxvf052+SAt5syeKHD+MbCTKhcRzbE=,iv:n0/z2bBOftRcAZwTlu2D1kUkyQ4uEPeuHJoBm/GNADQ=,tag:IPwA0h1FuzsVBMGjvZl8SQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
