apiVersion: v1
kind: Secret
metadata:
    name: unifi-exporter-secret
    namespace: monitoring
type: Opaque
stringData:
    #ENC[AES256_GCM,data:7awvwAty4z1rWPJxQE+Oz1M+fU/sXOYUQZB6Z4DUv3XNtPtfZpAm6MfyWF9PovLY//2nyzM=,iv:T+1cWk0/e7cwCdX8Ao+t4pNYRlRDYS8clkOY7EjKpHM=,tag:VpFv7ttEUq9gO4ZutZ+8aw==,type:comment]
    username: ENC[AES256_GCM,data:DhbCkQu0XxM=,iv:/Y7Umf5kAMH8sH4+FRkYI9QKSqlXMgLXTmVgYMJX068=,tag:HhkMkgF5gERHzt/BzUXiuA==,type:str]
    password: ENC[AES256_GCM,data:wXhL3eFrEt5V/MSlLtP724NxfHBePuw7rITVY2utYnwbQut5C575Pw==,iv:kE76yDHb1H2Zn8jo8sLPpSPk2FT94oFgQIPWsh08k7A=,tag:ixsukr36Nl+yXNCWcPuLhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZGJYTjgxZEVpYllSclpi
            QTBXVC9IbzJicldPTk1tRlZZNTRHRFpheVFVCmlnc3lyQ00rd212dWVZcWdPT1Er
            TjRlTTgwYWxMZHkwaEJQUHd0bVZLdXMKLS0tIERLVWVMYlE3S0JGeUt2WXQrOW52
            Z2Y3eVJUV0JFeElXaEVEa240QzdDSGcKLRQjbGN2SfVmf5KwhvsJQUOGoYnML6qe
            hm26F1TzGqOf+a86aUcnZyLBjI4Krb+KOLk6+1ZZ121OPZKaolMMng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T22:30:46Z"
    mac: ENC[AES256_GCM,data:ZNhZQPHqE7Iw+svdOG3wdv3ef/hrfdhSV/vYsXxaOB2lv8UA60RT/JnIf3Cm95GPptcAhEwnhQiQE1SeU+69f162bLue1D+29lane63Hy3LARaAV1jqfQpILvQMLy6WmyKyWIi0+jXFuBOdqqx4nz2FnM8K9oP9SXaoNw2uD5TU=,iv:/UK33l9hs6smBPuVwQmAIBY5V7ug32s1aPz0+CiQH/w=,tag:VD0VmEWfEitHegG3L3wlAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
