---
apiVersion: v1
kind: Secret
metadata:
  name: unifi-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  # Replace these with your Unifi controller credentials
  username: admin
  password: changeme
