---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
