# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:aSbt+dbIcOHxhD/B6eibSisWo5Mh0a8nr7w=,iv:AYKB7nRqILIHOtQw7ff7LLCjOytRHvnN3uJYYjtregY=,tag:A9C6mOWnJUr+Y8CP/wjtXg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:fWzTb2k5xaVP0vWqSo97Kv9V6/o4+WDTSGoEwIPiF2FPyiMazg==,iv:nLnXAtzTugVRagxQDcdoYKGmHCj18uJXgGr56AC2tSQ=,tag:1JsmAdaKYqHwjxBKE9w2RA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:SmEQUl9io11QKNiMmoYCThU=,iv:xP1CJsV+etDt1TuxgB22PhP5Vbe4rfaQlzQN6yqx3Tc=,tag:KInmhuVMEGB2gb50bZE9yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdk1lb2hJZ0tmRXlNbERO
            eHUvcDZ1RHhEN3R6WjJhYmIxRlpjVmJHWmg4CmRaM3EzWHFrc2piV2lhaTUrbzdj
            TUwzdzUxNk15NFRhSEJBYW5ndXVtSTgKLS0tIGZ1Vjh0MitUN2F4UDZXa1JGbnMz
            QzVsUnk1b1pSNjRON3JBUVUzdUV0VncKQXmRu8BWm5+X5lXafFTgnKbr5ZjUSwnm
            c6kiLfF0Apszl20nn3xufBo0E8IK8obDxE/fqtmLQPZCsw+vnwhYcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-21T17:18:05Z"
    mac: ENC[AES256_GCM,data:V9cqK6gw2WADsFFrLjKgEpTLYiLZ1du69BGoCJUJLJuKKwzdj5EY341b0tuxBzklLG7QQNrnjK5RZ1jvGPzke0KtsPfY/TyQKXPRsP/ZiqGhLb1ENUIh0WpwP6AP1sQNIugke6FqDtqLlXY7ih+vGGMkwiP7pNDzDvnWJ8rlvZY=,iv:YIO0Ht8SgLH8OqDuefEnWjBnMN4fubcJG0bbnUIfvv4=,tag:6hLF9Lz0emBGmyzS0r/m3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
