# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Cqzz8qXl5KA5FbsnEQLMu6K9KYOVNnHAhuc=,iv:WiFDBAf3WK6fQckvjdU9fT9l5IpIe1A83nB+/rXNrfw=,tag:izt0VbJ4HD7KKtjuI61F3Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:CA0ScWeCbAIlv9VDbaQp71ExDH5QkYHUPKAjzjK7OHi4b6/PoQ==,iv:LmsUmEpHkW+4UOB8blmeK5bT4yTct5l5xEYfSlVFtvk=,tag:um5UFstiPqW9osGMZafDdg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:XtR94TIcBOnGF3WED6s0HcY=,iv:frn4jTDXWEgL139DPgQrQ5+B8UUm4rWVkoLxqi5SWq4=,tag:KdpUiuBfEnShFeKtUfMDuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeFlMcGppQi9TSkZjM1JV
            cjNYRXNmTmhBNmJLM0pSVDRjZDBuNEp3eXhNCnZtbFhvNmlqV1R1bTY0MUVRWFhs
            ZXo3RjBzNTVtY2JZU0xmMG9kdTFEMVkKLS0tIDhEZDRGcCs0T1NtM0E4M2tmb2hG
            RzhkRFFjeTVMbUJEUEx0REZPblNGZDAKnkmyTS9hQLsO7NGukc7lGje4THzNOYCx
            OWKDSVBDA5L+W7vj6smw8XzL3eRnTMWClbhlLA5XfxbbJ9ZNtHtbfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T12:11:57Z"
    mac: ENC[AES256_GCM,data:epzZbtpJKaqmt1r+GLCuDK3r28cgArAexXyteaqYTXSzOx9CugjrJcSGbnMa0dHaUlGd3fP035AoBfa1Y69jKa/ouNMPdZ6Uwg6vql6zwi3UQQ/CBlARDqIYrTjEjabKk+RGQYhJ5bh3xTjviljQV+izmXjhUBa0xsKEGqqbv4c=,iv:6TUpEjGzA54n7unG85lIaF8cXYb1k7SsOgzcjNjtcZc=,tag:BkGfhSWFtNQwBmzE7VyRTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
