kind: ENC[AES256_GCM,data:Tc1YShgT,iv:kJAkdk1Y9M8zuK+npE7a957moxvuH+TGSfbsintsESM=,tag:zyEHVy1Yg1bWduflsKsUdA==,type:str]
ansible_user: ENC[AES256_GCM,data:8ECu2g==,iv:oWKdRDMNA/9nbEUrCbhDauWat97mxnXeovOMXJNJjMg=,tag:uM+nsO+IIpA2UFTx1IBJEw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tzQ424lnLHgNXgc=,iv:L7nKKppPGRFA6UqpmHQSMH6YCLNiOd9SnjhdHV18EXw=,tag:qZZrd/EWBLbuJTax2xrqpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWK3JWQkg1ZWIwS3pmZ2dM
            ZSt6enpZVDY2bS9IemJ1VDhNZjF4MjhwYUZRCkl0L3ExMER0ZmtyRFNtSUFabVgy
            eVQyRk44WVU2N21YWVF2cjFYWjlmZkEKLS0tIHpnV0dKQmNmTVEzcnd3V3ZJZ3BO
            WllJTml0Q1NNaUhJakRUek9WZnlla2MKXJlKtQub8wH/qHe3XmSpxpqkGNPaLGH7
            Gh6gpcs4ZaR1w/ivsEZpebJgzH7DVlzPomo1Kj50/r6sLHA2nbY6DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T08:02:43Z"
    mac: ENC[AES256_GCM,data:LWz9TLIue46lx2m+iq+hsKEvufvft+7g0dd1OxDhZnhcjBQgwirr+aR2wWrT08tfzU6jj9QrwqBaWHZnutP3hTzAbd+o4TID9THNVm9i3UO6wOkfMDaDUfdf68cWWFSRgS9iLLQSz2P6UZYQTg4yLbH07cqRc9hI35+EdK1Wjbg=,iv:/wmbXX9kaVYbLdd8jwYGshOZZ25MFW/lvqhvRZSaoX0=,tag:aibtQH0V0bs85wJrs/zXWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
