kind: ENC[AES256_GCM,data:24IFtD8J,iv:wlvsNl2/9w2Q+9ile9Fs/VeU47NxG/FjGMQeZB+fMKI=,tag:BevMEbF3NC46l/oGPAPAfw==,type:str]
ansible_user: ENC[AES256_GCM,data:IgrKbA==,iv:XzI8PTWBcLwu21IWvcva8Kj3uQ2Jr9cyewKVENpwl1M=,tag:BQbRadzgB7QD+dgEGSUaAw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:gJLhCX1tx+65IGQ=,iv:cFduj7hT9N60MNtT7jCCCmAzpat8BDIEwKR9VO9uzeY=,tag:bW+sNx9cKOoWp37kdGSG3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5akdpRmxQNCtkQis0dXpi
            N2IwdzJvWTBQTnBTaklHUGsrVFNnZHVybm5FCkFTNjdybzFCcUlSN05sczJIN3dI
            ZGc1NUx3d0F6V1NydnpXSlcralA2cEEKLS0tIDBiMmJuQXFaRk5WQ1JoOE5xdHNT
            WVdvTDgrU0I0VmpnelNjL25oS2VKcDgKQRRgqHr1EFEfI7JO8jB9ny5sxBrk6peB
            SPAI/C9yUFrK7rzhHN8mKrOqh8fAvzFcAzfcAlUOluoL0FbmGWLnmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T14:46:28Z"
    mac: ENC[AES256_GCM,data:OJqop3b8+2plEpPPd0BdgznZlkSCZnL6n0VRiJVeZsvPwcLxis0mlqKA/8MAjGZ/AobGiPO1vLkEMb8d6LIesEoWY+PAZRYf0mKmPMMFYYGJeExTDkZlk1JGXn2vlhZ+9JFNtI0/iWqPl/5LNcRETae3YmAfxHskAtPB6o+Gz4w=,iv:Jwr1QlNTSTWpdCsW26AOyNH3KGrL6d2p+fxJkrfMPHY=,tag:1H5TSF4XwyIMzW98yzVDVA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
