---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.30.4
    env:
      TZ: Europe/Oslo
      ZIGBEE2MQTT_DATA: /config
      ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: "zigbee2mqtt-test"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant-test
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant-test/status
      ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
      ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
      ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
      ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
      ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
      ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
      ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee.j-burg11.dev
      ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
      ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
      ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto.default.svc.cluster.local
      ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
      ZIGBEE2MQTT_CONFIG_MQTT_USER:
        valueFrom:
          secretKeyRef:
            name: mosquitto-user
            key: username
      ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: mosquitto-user
            key: password
      ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
      ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
      ZIGBEE2MQTT_CONFIG_SERIAL_PORT: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
      #ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.1.90:6638
    # envFrom:
    #   - secretRef:
    #       name: zigbee2mqtt-secret
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:zigbee
        hosts:
          - host: &host "zigbee.j-burg11.dev"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: longhorn
    persistence:
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
        #hostPathType: CharDevice
    tolerations:
      - effect: "NoExecute"
        key: "zigbee"
        operator: "Exists"
    nodeSelector:
      radio: zigbee
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
