apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:z/Vx/uGeNLTTIsOvJvil3BUppJE50SkPs9Imom9K783o319U7Qwdbw==,iv:gM0kGoigczXxa1mLZx8yE4b2FXhfbV/l0Sy3l7q9ZKY=,tag:YQWYqAGynpqvtNOVAjqiyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWWwyRmM4bjZraXMvbVRn
            QnNyd244WEkvNDdlazRlNU16M1pIdWloNlYwCkl2SE90TEhobC9NMDFwR2FEVlc5
            OG52WlNUYXZLai9zd29oYnpjR25XOVEKLS0tIEhES2V5U0FVT1pkMmNybjlHVXNi
            NXFEbitlcyt4am9Xei8zYjkvSXY4c2sKVq4H8LL0O+1kAvYzvSt+yLF4g8Cef5H6
            q7ZCmGdR52mvpf+o2Nqr0Pk6GyFXfwxlx8gdt/E8m2NnbzCyZ1eywQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T20:24:12Z"
    mac: ENC[AES256_GCM,data:mfLXmSsq9N5NwhSFcNYZ4ZUU46jKXDbuyagzsbOZYUJkaZOtLE4HE91XGcybkBBnKB6BDRxYq2BGeOrV9vhueUDHXvR5eOHmy0C5P42PT/glp7f9+oflvkRkmJ+cNBYLLlmXVdQEFtRams47USL9ppjTSubUFZmD2LmgM7RxjVU=,iv:C0LGLPvylCqv9qZNqXYHVJL06a0Y5qKNxOUeU0bD4HY=,tag:ONdFrhxCRo8hAs0I+cohxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
