# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:mguJtW9B3YZ8Eq9+4mDuRWICEK9doacfjvfM6fuVirmGFjTR4Q==,iv:eJR0tZ973KZ8vAbM0xlZK6XsMgFc0uyVuR+le3xzIq8=,tag:NeA7Lf1pCdwngc0KUqP/4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTllnbjJWYXJBY25SRUUw
            WUs0WndCSkNhWEJKNmY5STdycVRBRzlWc1d3CitKYnJJcjlXTTlGWXlOY21BVE82
            U0pCNkJoaExNa1pFNjlPbzJFdXpXR2MKLS0tIDVSVlllZlFOb1phakRlRHk4Mnpj
            Z24rVURreW9hK3NCekNJYlpHOC8reWsKETtsUFTAl/nOsgVhsAFnvBYht3wIpk11
            e1cPtsQWNaE8YUoYtJRykojBsjUwaj/t7gnsJgjv6WkANKlt8/bSiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-19T18:57:12Z"
    mac: ENC[AES256_GCM,data:q2aF6Yl/gHtrj5RlS2P8m5bf4l4goOvX2YZRlzH0MJgk52cY5lWQj6CnojuUCrhA7yWolFAN1qwXp+v72mnHgvK2ltE14Y13MrbuZv5Y20NzN262XCbNvOVWju6WtsYtbJL1bfYiHpHAPIfUy1YEDCfK/bYZP9kA33lUAI82Bc4=,iv:RtxaHfJc8MfxbVHt4+94px+sAYhAeEIvGMHYDR8NAp4=,tag:j249yI2VdxtoJ9lzN97njw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
