# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:vnHzTSGSOzps3vsphqbf9m3uUZlUUKuv3tLiFY9kj0YRwu3sTA==,iv:JD/SXjMZhVaFkRw+CfvE1GlKWLAZeQh5qbau7cyOmRQ=,tag:7UMwisxrCrk6dLjgMfrr1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERHlVb2pPWlVUNzQ0VmpQ
            cmhSYWVsT014WjczYlh2Y1BpZUxhQ3ZyaVcwCkhrRVBUb21wYXBPWWlTcFVuUnZW
            VFpid3l0VkFCUzFxeVhSbVE3OFBqVkkKLS0tIHJFcTc3aDdUL2l2elJhMTQ1SWsw
            UmNOQkFWeUxWSCtMMXRjYlZHeElXSWMKHf4OCKEH1z4+clLA/3YamiUqP9CmmoN5
            8+OM1pyifUnmKmACY3Q4okx/Mf1Z49jAqY7qZE4G+u5Xodi11xjvSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-09T15:18:46Z"
    mac: ENC[AES256_GCM,data:qrm94euSPREnTsD0bdFGTnaB56+mHxiMfNFlhz4r629vr5ZnibGHIuMRTNHcgdi1cCJ/67hKMZwNdidKPrHH3EiKJInSwiA/X68QwvhCd7vcIJAk1EUETVz02gFL1BuZyKHqG8J/RkTNdh3cW8+y9LV6Wzq7Hu5eu9KMufJ49z8=,iv:kiFGp5nzR7lNpPs7G7TrgOH0e0E5reJXwAVh/i7SRD0=,tag:8eTlaS/RhwOBBLf1DQvfQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
