# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:qncwQ+HsVg/BapJOjidmr8vMaFJiCxrnOas=,iv:QOTgnauVUVsbi2/2qaz0ghktTYS1wwBgpr2XnPRcS+U=,tag:PNhizu7vY3giVN+4/LZh+g==,type:str]
    api-key: ENC[AES256_GCM,data:FuL1gzsWeCUw/Edck7Dj0ltfsdLC7c2/jxBbRsYQ9VnU3hDPqQ==,iv:G3Pbqp0jttjM8mp2KOra703byuLllzoQ7s4lD4KS3Q4=,tag:i7N37etq+Yt5L9JT4+kmhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT0RFUzlNbVNUVU9OSzBr
            Q0twN3lXZTRQNzI5MlNEYlBzL3pvNlVNUFdzCjIrOVM5eEN0SWd2WmVFVHFZWllC
            UnJ6V2d4S3I0ZFhYUU5RQXd1RnU1VkEKLS0tIHEyWGt1SVNKTXZUMml0RjRINkln
            NGhoN1BuaGZhSEhnVy9Tc1hvSVhiN3MKG8fKmChm+u1IT2xNAxRvDFay6yMFjbZo
            8nsCvZjWtade5HbzBe2j5+bIel/78Y2OifuWlpyDbBP9xvzaPsPlZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-21T17:18:05Z"
    mac: ENC[AES256_GCM,data:I/qA0JjVY1gSCdo2oQpgANqBqELIA67bZs4abTwGKT5kTQ3kLylbvFJGfaMj+Hr9I6LG9pFiiwDLl+r/Qb2V21UDPw/9hwZuZNBgW0u6ZPGqUgTlR5AiUmx929gB0r9yFu7NQpVznyhHaugo2cIySzlAuaFCbqeooefpTfLqmZE=,iv:f37wRuCkx6NnYUfFELov+gn68IUYsAHLyr2JCxj/4UY=,tag:f41ZP4hctiJ/z+vvLNff0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
