# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:r0nL0y5O6D2nGo7mnEtrkDoq5YxtVUTllSY=,iv:nyjbrVE1pFCT96GtYedaEGb2aDztCSUv1FamddjT8dU=,tag:ffBmZXYiiDO9XblAdgV3AA==,type:str]
    api-key: ENC[AES256_GCM,data:HSYpu3Tm5+1YdB2Ou5YZDC72EcalElP8h7tuFp54fXS+pN9oHA==,iv:lYKaA5AZS6bLj1KlDjAH9mMwnokRkkeVy1lGrwTOBFU=,tag:pxs8sYm5d+oEmuh9K39p5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTDRHYTlYN1lBYjNGaS9S
            Z1hZeFBjOVhJSTd3amNaRTY5eW1qSEhjTW04Cko1MlJDODZPVWtjWitqL1JUb1lT
            NDR2K2lCNk5lajdsWWo3bU1BdGtKUlEKLS0tIFQzZi9VZU5oUHMvdENxVndibm5O
            emoyUGVOQU9YUUhPZ2d3dkdrcXFUSGcKjnYVeDjiJKFhGAYJQnAIIqelVK90iJup
            Caz2hon8Raf4x5fWW6tliWNm6zGhL3LfcYOtqbRFHVncGHJjqkf5/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-25T17:31:36Z"
    mac: ENC[AES256_GCM,data:Wk7sWzayfM17FyD9ojG1eN1VwPLvKXSp8KAbwdbpxgRaaoC/XBMC0GR9mkbpI0REdaT1GrgJKDHQoMaeUJ9+SsHKpcB/HgGiFzjtnllsOLvT7m9RPscFeTWRAIm3PGqqrcbyorqyOa/4vnPxRLEJmJna0ZPNcyMT/Rs+p7awXFU=,iv:V9XOgv612Zr3VAaUc+L4Zfger/cPOGHkauS6k4WMCME=,tag:Z/dVASaMk7eXgC9y37KGDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
