# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:l+Fyi6k4aGLtXQ0SJ7XnCFX5B8NPn+/JoEs=,iv:08uak7cwBHRwLXld7s55KLOtpvBKLu+LA7TSCotQuQs=,tag:pGRD88L0Bo7tFtV1tgZ0gw==,type:str]
    api-key: ENC[AES256_GCM,data:jg8O4VN85XLa7jNsOAarl/2Ize+o7/kIhmCYIgjHMOAAYu7zcQ==,iv:/k5/L6QFMs2tj/Nsv4+l2T56nTl/Ohex8+0kk/fyDFk=,tag:CszGQrwhBjbFUsLaVzcjbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUjgwYnArUldnQ1VYOHhM
            eUtTSk5SU1orcklTdzNZd0Q3WkRINWYwZVRVCmttOENTWW8zK0djTXNrQk12SFgz
            a1cra3FnWWtWc0hRTGhIbVovVVM3WU0KLS0tIGFzTnF2NjdSUmd5TzcxSEpOOG1R
            blhKSWI2UVlFVC8yZllpS25abWVOcW8KNqEUiJmiyM8NXm8YQzrn3qmYsov4yXfv
            knuuE0CgG8TuRfN7JomNYVl1qETqGplJMWVtgcVO5MpHp3/CxgMKEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-07T21:08:32Z"
    mac: ENC[AES256_GCM,data:qlPb/t04WtmdIgrDE0hlLJCrljBNnLVeReAm6/OuMC40qALcw+UURrzCW1Y1OJ7sYgGtzQhHAIH2sPj98etXiCErYFf8sxJKA2ZNfwC8c6YjX2k3CBY3PTadQT1A3Z4kotQcyrMBgj2B++rA2eHbLX3A/Re9yjgXt50x16rNwGI=,iv:GdBkkzicW/JIh1x5sQ/yiziETzIXHV78aowuxjRuUVU=,tag:fPe8I0nTzpPjHzeD/o7D+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
