# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:xt/fcX8tc3j3vhbbFkeBPyaBG0p4H67yF3k=,iv:TVgvqFK87I5imhhE8S23Hg9F9uPwKuJGZS2mCtFAOr0=,tag:DnUPlx1EZZV9QWZ5D5DFBQ==,type:str]
    api-key: ENC[AES256_GCM,data:1dXwuImuK6LO49i7TSVqrLbH+pVQjADtLqHy1/RommsGqu+VZA==,iv:8roHPAp3ZF3hBDyoFYGGJrOu1Lgt7KZnmF3YutB4YAw=,tag:h+QupyXKs3azvu+TkB0AEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc2x5N1lEeDAzWCt0VklH
            SHd3VjVqaGFEbEdvMEdqNzFFKzN1T1M1bG00ClNvdm1wY0p6Y1dxVDBWazR5QVJC
            ZXZjalY1ai9oZVRHRTJJbWx4bGJhZXMKLS0tIGxMOElaaVI1N1dBZVdmWUFGQlpo
            VGdHNWtUakFxWjVpa0ovU2pTNDVqV2cKUy59QQEvj0QoyUAM3sjSBvhJZXYExFM6
            pwm+y+P853vQVGYhd60ZlDjrtZ39K+0oOGknYLnp/C66oJnmT39ThA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-10T17:06:05Z"
    mac: ENC[AES256_GCM,data:QJaqxyo4fXpUfqjGl0ILrkbEc7PGfmdBgYeGpUH7hbMRck65b06I2AB/N/3RsRB2y+OnUTWnDbSX01pAazdwZoz8a++J7cICCQHFkhPXjwqd7EVwAvwsGdo0UIZJFGfx+qotkcR9RuPMSZ8rhd9od5ugJTWsKjK8B/XlGTvDtvI=,iv:su6X9rj6fXLjf0rsejGAfM+1vdKpqd5rZnFoCrdHrok=,tag:OqgeuiHwbqgyL4/sVDvc0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
