# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: networking
stringData:
    api-key: ENC[AES256_GCM,data:Klp3hjNff7kkBYrfP8TzkrPjbr89KHEWGsh6t5hPVx99QEjjSw==,iv:a8Qg457J4vN1UuDUfqAwWPuKDSi0O1ghhcTIiZBeHYE=,tag:TjHyQ/8s3e1h874scBOPjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbnVrYUtmUXczUFUxMERD
            L01CbXVIQi8vOWFGelBlMlNITnNDRExXSERzClQ1K3JSdXFTb1lMbkJzTlZoVWN5
            T0dWdXovbFBhWFFQc2JnU3NGUDVUYUUKLS0tIDFJQi8vejh5Q3ZsQk5qdWl6Zlpz
            bk1Celh6ZEJNcGtwcS9lRGxVZkVJNWMKe1+0CksHH6dRe3UqsOVw5NzjCzNquqCB
            lUUYzNeK/KyOORjwnX5hLCcPDZKB0UC+fInL//Nh14rcr82KruNBiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T23:19:44Z"
    mac: ENC[AES256_GCM,data:TXszMr7z+V/z1qw9R1KHP9p/AyUGvFVs32diUTTXPylj8qrj8kaNNqunQ2DgJYbtmIvuHZ4KB8gppRbfv7DL/bONQy8oMu/MDCoW6/2lgYKvZX6c3XOLw5F5AnFgFPGSZvGvG1HYrYhWIG2wgXw7Dlvl2x+GfXpr57qvSjav6mQ=,iv:Yx7rs5qUA5HzmZTcZnPK6f/84iFZDB3XMOP9C6ISda0=,tag:b5QfAp0E1X9c3Jh+NvyybQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
