# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:6tyW46plogMY1EO0,iv:sBDZGxyXWqu2ELTtO/Dy6+AMXm20unWrSgdG8BbYqCk=,tag:40JUIZcXwgK1s+Pt4xwcNA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b96Rw3a/7C44/D47lUMQHnWjCCnATpjUUUE=,iv:2ackYBXh3m4u7ui1NfbRidYsYd2ONJAWRrAb9pcOyVM=,tag:u/kNyMBY8Z+A+gUQYKeKUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYjh2SDRSV1JoUnZPb1FP
            a0hvYTFwZlYwMjdlaHhuMzBpQmlrWmVnZERZCnREakp6WUVFb1VFSld4YnVnclNB
            SWFTMkpyNFdVMEY0Wkx4YWYxZ3R0eVkKLS0tIENiaFlEeUxRZEFvWTJIMVl4TmJL
            T1dxTUNLSEZZWFovdzg5dXRPNUE2YmMKdEp5DkMgrqDl5nJehygtHcb0otMIvPnJ
            gOE6IOHbMFazGYmVkpQX+Wbz7CMZKaDxsKgiylM8hWEMhpHGypuXzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-23T10:34:51Z"
    mac: ENC[AES256_GCM,data:WXKXjfEsY12MR1l6rphU7Za7n6F2AAYsSggXuoeS2sccjAW+SzTWianfNQup9DbVNafkkIhQNpAbxj8cxkTrPL+Ycm5Yo3ZhWfVf70iqey30aA0qrHJ9HQq/HR0vZdgksAZG2yeBB4PfGAIQ/Gu+wfjFHGPUyMZZW33PeRrsM2A=,iv:rZI9JYkQ3XNIjUQeAh9YP3FPZYK3i9TDr/7LNzIpfjY=,tag:oteoYw69/e7lcGeU5dU1kA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
