# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:uukLhFhM33/MRhaP,iv:/wb2ef+PLcGHkj/zZ6SopqdD3DquPEZDLi4iR3CtIoA=,tag:aO7dIOisXX4PvWKyu7B5xw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZPJLHBy6J0at1yTC2p0OhILnKGsZDdxFsZM=,iv:4euJQlubBfsbmjsxOFxajD4dCCq9RVSSpFv48bx9uOQ=,tag:RkRbx1fdJ3fF8g/zs37DiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNHdKaGRSMkF1ZGRuTU4w
            eFNrK3BVdDN2dEJncFhPbUZmSTNhOE5KWmlZCkY5RHgxRDBxWEt4eUFNbnovWWVx
            SW9TNjJKNi9rODViVExibE1oc2I4dHcKLS0tIGt0bCt6Z1o0czFJdlRrQVFleFhW
            V1JIYzM4aGZLblNkV1pNeVVWNmc1Uk0KaP7s66Q08cV5zmb1DUWZxn09w6TqaEG1
            8ynRInAHyYnZmJJvzRoAImn7isBMZoiH0H7lipSQFUAnXQsfaom7Zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-16T22:05:41Z"
    mac: ENC[AES256_GCM,data:Rlz6Ufas9GVFk5gMZWS5VKY7skx6f0MGt7b43cV3hxbKjXqlt/+nNt13mLwADaHTvhyiNRBlnJoyQH/l1W/i2XUJZQoBJo7x6XhD1iWSWQMm3c8Km/TcmfpeXXUC+Lw5Z4JG45zFTL6XXDJ3Lf03b4GeDrgVqVFuFLFYKKXud0o=,iv:HDZrcUdxunVb6l9L/DjLwZ+e+xkxOSsXQE4ErHZsEqw=,tag:85y/jPa2mEsRdCeNOM2gUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
