# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OnAfLXZRuGWlBxJ3,iv:OGrjRbFXj3rc2iXSk9mgTJMWEqBzY/lT+EaRm6rHaqs=,tag:M6bq/sy4NgR4OgD52BZy2A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7c2s+lTv5roZASgMB2hTjgOL8VDu8bHm2ak=,iv:Xs20XESCSNVOjautrUtwsubVNtCQ+m0OzPVHLD2HkMM=,tag:IKJoM/E3w21KdgADsHAtVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y0mwesxaja7ytptxj5fypanamddy9xzymcjcd6pdyns958xmfd9qn2lms3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMGVibjM5L3JKbDR2K05m
            blRFc1V6cTlGME1qVzB1c296OUFqTHB6cUNzCmhWdmgrRlJobnJELzl3S1k5VVAz
            MGVYTXRFdFhUbzdVTHFRWWw1SlJRWEEKLS0tIGI4NHljK0c3VXFyc1hUVThpTGI0
            L1dmVEEwQUYxU0JHWGVSRHErRHNWWW8KhCFk73jDqeJaAHhsSamWKxqmjcZc6nwh
            natJC97pMBEKeUtgC7lauitsHHwnHHUIOC1GKxa8TPhzQ3kvgRmnTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-19T18:57:12Z"
    mac: ENC[AES256_GCM,data:vu7nXDmAhfoLatXiGwLD6IzTbzSuFZpbYd3sp2vAcAcQHg0EfbCsr3UszI/qn1PN2jcjEDJoT6KwZT5SOjJZ9kYkHOjjm6Ze2RFpf8Z3IqDzIGe9+Sf5S4iRCsg6e08v1itjeDTfsgKB2HATmxVTkcBoIzSrhwKHgX+HTC2dVFE=,iv:lsNKbOXWcDrdb3DW7NyfYJN7ujV+V8/YoEnT9GcEnFA=,tag:zUbv4CqP9Et7x1Tr2Bkk6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
