apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:93c5RUAX/ugx2imhIm1qFt/dtPqiwcFn/7xKUxKFV/YWCq65kQ==,iv:KALXbxf5BpfID47saXIZiJYrsvm08ktrqJ4AaKLCnkk=,tag:xiecC/mu7M7hjuMPPJXjAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT2lQbzBFTUduUDNmMUtW
            ajQyV0M1NTlFVjNIcDZrdGFTUVNYZktGV2cwCjRRUTR0M2s2NGRwNDkvNXRKRlNm
            SytiQTBwQmFxQjBIWU44TnJ1TTljM1UKLS0tIEMyVmZYd0tkU2xkTS9lS1IyL1VG
            c1JxSXVwRGdLcTNGU1N6QlU0VmZwcGcK2dZCkF7DmTxb174ks+CKIqsFtldQe06m
            JR22Hg7wNXVKdZ6asPg3jdHIEOkOentWLxFcxOC7jcmN3fgbKdxtcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T08:02:43Z"
    mac: ENC[AES256_GCM,data:edyEi2OzOCP0iCRnH7p5mlfZo/Eyc1hTkG8Vy4fwYKGbaXaj0dk6EDzZzqh1ILxP4TVSvuZR7MXYCBK+pTdpra0mgbrStZ59in+RwvPVKM2Rm+oJbXC5Ayr7SdQGJZeP/XjkAPbYx7V4MrMO/URewidVuqXNJihuECcHL5p1ncg=,iv:VPFRxD36wCkvnAYqN7E1vLDxayoJm9+zQib/pJ2g0GA=,tag:FN3Nhgdufyb/gxre4Dr/yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
