kind: Secret
ansible_user: ENC[AES256_GCM,data:ut6hPQ==,iv:kHEgvTN3i4zKygSh3TQqGLXVlapvnO+8+iMhIEZ07CE=,tag:ah/61+/ymh+/2Ldy9bMUQg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:bPY7nZUkRzcSOzE=,iv:Vz/sjZTooA+Ncx+quIgORKHVL/2G8Ekwi/I4SAjsosg=,tag:fEE7NoI3RgcbBtF4UQpcgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycXI5N04rZEdyekVDZ04w
            VURXcUdybkFVYkpaM0g1aFRFNEE2S0RmdVRvCmY0bytZY0EwY3NLZGxLNG1jRm5w
            YW1LL1h1d3huM0tPb0VPNkxkcHlKZmcKLS0tIDFwUi8xR3k3MEp4ZVIzWEF2VWZ4
            ZldBNkFNWFFCcE1sYTdTT0RvODluS3MKGkny+1ZLotHVkaOMy6AEG8tnzhi4C92r
            piRUAk5Tdf5wMFHX0dRWDp1RUwMMVAU8gF1n5LXb/8aezKAoByn+Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T23:19:44Z"
    mac: ENC[AES256_GCM,data:R6K1BQuJTIY42U6ksLOBD8s8NSxYBA4pImvOhkGRL/zzyIoS/YsPdY6NcCzGCutUFYfesz84kVjnZKlYA16l9Jyb/C+ItgTdfgI6SWODuHUVglkutRLy45aJBqZfHfhJV+9se/NtoZVNtKDhV+8e7lJ+PLMoe7fVGoQmUvuW5HU=,iv:Bc8bknEW0bT5RSeKA20bRdFEjyELVCxaBlYk2NOKk2M=,tag:YwVRlG/J1EYU4t6de647GA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
