kind: Secret
ansible_user: ENC[AES256_GCM,data:ob1WIw==,iv:/+aINQ7xWEI4hC0nVKdlnDRr23Wp/WZU+VrgXXjzkoE=,tag:8LBKn54ROV5u2kah5qVm9A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:0zkRyNbttJX6bqk=,iv:WWjMlYu3jdmjySCBrhx6u9zsuEwf1bzzJzcUFq9oWsQ=,tag:z77/G7ieJXGE70urhFC9Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvb05OaU1PWDZpamcwMEMw
            YlJraTJ6SWNPbFNTWnJBY1hCQWJpMEFtNlVVCnMwQXkwcktQQVFCTVQ0a3UwTDl6
            WlptLy8zYmN0UVV5a2FXbW41MzlveEEKLS0tIE9ncU1jU2lkc0NsZVhlQUJlN090
            TDNjYk9GdytBK0V4K2c3ajNGVThZbGsKMEfsdhlxCEOii/X27e4aaGjWnJp6aas2
            4exitg1a01wnDBDcGP9ednQP75xTlaLV+Ahoy5c8R+Y6ZqegmeYyOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T23:19:44Z"
    mac: ENC[AES256_GCM,data:2o2KVHlAOMCvufNM/HFDDWDgeRUfce4+dBYEzNEePfMOYkQbe4UXbhq0PhoJl2RKdlGF5uWBcHB4IbCFWTYIi+akVkiMrw3MuOM39ShaNxjrDIlXY79l7eHKcSPn6FA37juiQRv22VxhZfm+H5VP5+MHmwUcCy70lmyEdIC+qZI=,iv:WbjYsMb6UF6t0nSjEnEklcFKzkNUBWz2uZ7XURvwGtI=,tag:miUK2pzu4pfBWjOqoOEzOA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
