kind: Secret
ansible_user: ENC[AES256_GCM,data:vQwl0Q==,iv:rL9E8EjEhONS9zh7f4f4fLApMoHCcnJOlLFqQ4eNbwk=,tag:2d7SI0q79cy9e2EEESgtlg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:g3V5WbeY31mVCn4=,iv:AiupG5xQrcxBxVLiToSOYdBl3Htv57QM3csn2tPXWjs=,tag:Yygztey9O18TWhPUuOSxiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBneDRtNTJNcVpmelpkVGRG
            WjJQUlRCbmp4VUp6Tm9JeGxZd1NvenEzZ2g0CjBZTDZzZUZ6SFlWYVMvcHNMM1Qy
            SWI1Q0cvdGhNaEFacjFPb1lteHZlWWsKLS0tIFlBODIxOXl0MmswbE9qdXh5RHdl
            SGNUWXREVjdDdS8wRC9Kd1gzamVCQUEKNF1QVEMbN4LQGKNlx5YPf9PaA/gcgyMZ
            LiQBMXi0CFKcktW11/8S+bgKpQv5KX3TxjMF0K23nDmsyydXO/pcOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-23T10:34:51Z"
    mac: ENC[AES256_GCM,data:atwjL88ivv/adRRVz1oA2JcpIsD+NLG59b8Z713gkQpGVXkuOFYkX16lyI9pD6NC15VT4DpDEqm6qu5LIzZR6e64jz+BsWVCktB7sLlGmgzOqJ71p/AGcGTklU/Ragyker/95QjIbBFz+Pz3A9aSblh6AEB2xUGxm+zQWYcmFK4=,iv:VWVMoDelV81B1SYX75jKan6QxglNOVdy/u2REhuX7rc=,tag:mHpoz1DIvdrjNyUaJtxa3Q==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
