kind: Secret
ansible_user: ENC[AES256_GCM,data:PoavLA==,iv:yf26UP/l0LaeFxl03GvYCo2Doa1AMWMu5jfpWgYdt9c=,tag:JQxdn/kdVEFXRImvjYagtQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:9Ud8AGkPUlyZ0W8=,iv:EESBbGKiewe2lgd/Q5T4yBVlXUMFvC+Xs7D36/6/rBc=,tag:I+5OgPQw/cRL7GAVKLcpkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhLzhIQXNXUEdUQ0JTWFZu
            Vnl6WjlIVDkzTCtsdUdvV1U2dXEyMWZFeG5RCmZwUVRORzQ0czY5bW1MVnAwMCtE
            TTYxM3I0WlBEeGxxeVlUeGxldGJpOWsKLS0tIDRVVmdaTmR6NWdlajB2UzhWRHIv
            S082K014R3dLY2FPb3JpdzRpRlB0TEEKUCOQHWG7dJjv8BctxsuWjZNz7MsKaU5I
            1JWnmO5yRyDoGe6dR6Yf7F9/UhvriSRRD0wTfQHllAqB3U77IQ/ifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-23T18:38:26Z"
    mac: ENC[AES256_GCM,data:gTh6zMLpb0f/dcrjAGpdJG8pY+nZ/7+hAZRtziWdYTp9rA8eUFITpxt3hBwH5kQjnxYYtwjCWpegiwtFBffiiAKH3pCMQRfelsGWM6h7UFdFYFkJB4uW/h0dfOY4fgZmQuW8FeTsocqiKTvETQGyKHS7CyK5KMKhihhUKHjCZlA=,iv:WwFZcM9rN98fWy02wLEoZziH3VtiQBXdtVLp2bJPQPs=,tag:4qle1PUYa4Uk7+gJE9ZVbg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
