kind: Secret
ansible_user: ENC[AES256_GCM,data:8kMLQQ==,iv:fJC4LLmYry0Cn02fkeMnO25x8sCLGdATjOO0M6a41J0=,tag:ravKtMXJvZx/VWURA6zxcA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:cmIRlbcKBbQZL+E=,iv:rmKB3BQdm0yhbVjzV5yLcyFTqEvR5M6pH4aDECxeQzM=,tag:1EBXpCS+xxWS2XBuSZYl+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQ1kwaVA5bDFEaXVtbnA2
            WGg0L3ZGdlJxRGxjWVV5V0g1NmpiNU1UcUdjCkxwTFBJazZrejE4UlIwbnQ0Nm1l
            NnZZQ3dDcFFrS2JJV2ZnOGpOTmZKbjAKLS0tIFI4ZDBaWHNPU0Z6YTJFNFRsU0tw
            b2NSMDhEU2pDd2RJWk0wSEVLUXJ2MGMKSKVaLlP1kOm7zNALLF6RHOmfQ2Yghvnn
            U2r0FYpXQfoGULidHspt0n7BBld3y/n/NFOsiLzznJ0rOpdFTMJLkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-23T10:34:51Z"
    mac: ENC[AES256_GCM,data:AxgRLqSdyzbA6UwULsQD3i/4iEZKfZPHXKCmtMnePxOUwLfKbdT3tWL9xhl5Fh0IOlhs/bQhCgN0oAlfrWCKwdih+iIi1vQnUw49V9iWgX3S9lKxtprerztIJmVSXwprEYKcXH9+nUNteiyoI6svALq5aitI/fJrV07GFjoquWA=,iv:+3aH4c8iAo7JQ/O9HMJgDdmt8NRGJrA/754PKXbOziE=,tag:FPtQCFVQyZ1b+j3tVRdrng==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
