kind: Secret
ansible_user: ENC[AES256_GCM,data:3gniIg==,iv:ipofonr6jgBVcuy0Tl8rPu1UpkMtUfiXzMki35RAMEI=,tag:DBJhPbSFVzu1DtmgrjKRqA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:i7inhqsNt7I08Ho=,iv:9Cka5pS48nG3z2B3jiKj2rbaOEMK+jKLpbaGubyRmPM=,tag:NPu4e+3nZED7j/HNruWiSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUZwODhyUE5qbTVYYkRt
            clY4RXEyNmp3R0FVZjREY2pXSlM2VHZNQkJnCjVhREhCbmxLRE9kR1RMWDNIUVBC
            WHNVMFlZaFNPaTludk5pMVpCZWV6TDAKLS0tIE02NmV3RVE5QWJhempyK05BaHE5
            SXh3QXMzRkFMYjJIbUN1M2xlT2hUblUKGkmqE5zf2LDj/9YNl311UN7f3AFvWBr/
            daT/+NRzpn0TLGS0P7whWVd3jhOVHon6jxZWtXiI+migmdivNhIm6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-21T20:30:24Z"
    mac: ENC[AES256_GCM,data:1U3v5Av6hZmVyAfTGPxYjAEV/+CvHruJpUp8UtQFuSVN33bAcP1aVOxS3uPZv90R8sJdTqh0kNMQYQ8xF2ymIGRKSDv/1NtlGIwRAlJ3ca/WeurQEm89qkYCoFLAlUvN/VQhYXFHpjowZx5ATpGToeEs9RteIdcEIsvPNun0I6E=,iv:s8hY4Li0zIk0T01YZkSe2fn/S5G+ZSt7GuVPTvX0mEQ=,tag:exGsXH/vzUEjQI77Qpfp8A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
