kind: Secret
ansible_user: ENC[AES256_GCM,data:ufJ+vg==,iv:glknb2LWxEf19R48SmlQpb5+AtI6z0yLNphYqajCmBQ=,tag:gSEfT1wtvTwHTJiXR6sMow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:RDwI/speHcDTMeg=,iv:Rv7H0ZosLmdGPKbu4MgyMair4e57l2DmQafoIvmiyDc=,tag:/xFMeG15UmgulUpZcouMWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hzqcn3h9jdtl27e78vfsc3zuk53u7ud48r4564489vjj6p00a37q5wtqz6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMlFFOWp1UHh5WnRicWJO
            a0tkTlo2cVJtcE8vbUV6SWlyMmhYQm1TOWtzClZiK2FUVTZhY0ZQaUlvL3Jza0VC
            dVhrSnpNQ3c1RHluSXJxVjZXbVZLL1UKLS0tIDRGNzkvODNiRFE4SmJjRkNVQS9v
            bk5jWHhoNGZkYlFOR1pvUHdGTXJReTgKP1KjESiryzUnAJJlw+LbUSwWEk1f7zPa
            8Jmy3ApvJPpyCk49Pxulc1f6RYPIYKbBtCH6PkJypqUFJ0Tdj9jmXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-22T23:00:37Z"
    mac: ENC[AES256_GCM,data:3GIKeA5nuvcrow+01z9y0r/bRjpI6H3psyY63F/uOrzHEvPZLDjlrX/u4o50ZvWr9TR7hhHrhFR1XhP9Is/yL/YyDjJln6JSNpVW0JnMQCvzmG/2oz+CnIzkQG8aD9sUmwhkxP31Hnt9gu594O64nNQGAVmhzC7bhB87QHcMajA=,iv:YgP2+kQrMUeOngiRlE5u4z/yyJ3WIQzrMd6L1bYI6Cg=,tag:umJO5m87y6aj2pqmrVy5Tg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
