apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:1eDPOLClfWdEQVjxYj3BLsB+yR637FRY3jY=,iv:KDKR1wiHo1aZJpihaZfKs1fQEk2HUcokEdIvzJMgByE=,tag:1qWeOxG3KxpWFQadZ+WXBw==,type:str]
    api-key: ENC[AES256_GCM,data:Z7/rJosPOwnSX+T1IqE5moqK4etQyuWkaPmLYDrDf9D55mV8sA==,iv:U0QCgJfvbjfDCkBwGjLnTI1tux4sPgjdEjOBMLSP1mk=,tag:JFIFDQu235LSpeUaU0KnvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZHB6ZXErMExkK0dFYzhC
            bC83akR0d3Bodmw4VDFBaDQvVllBbXFKbEZBClZybFVURE9Ybkp5NzUrTFBzalE1
            aThMeDAzMVZiOXdrdTM0azIrM0VIdzAKLS0tIGtraHpOVDY5blZwWnRqdHBNTEV3
            Rm13T2ZSQWs0ZUFXTE5CVCtLeE1UUlUKKf32eLBYxJuyuNxh4I8lqAmrphRFgINb
            4+YG5IeZ7BpKSUTQadjrIw58Fcc8SxYJ71TttacXm/D6XElDZpwvoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T08:02:43Z"
    mac: ENC[AES256_GCM,data:S+ZOITgkMA5LJN+JSa4aprKlIBrvBtyA4+O2gCuNh+tiLNiAJala6gdpWENZNrOJlFM4tID/SEmg45l9LsqpAi04K1mbJ/WSB0dcdHdLCjISER37RC7vX2sxlRhtbbYVReFgl6toWhJnGxcYwwWzZRhMk5NlL9qx8XQXiiquH9E=,iv:pjfzMtw0Ck363x+plXD/SMz9qNiTu0AYgJEBVRKKPbU=,tag:eEuNReWITVeTSOR842/FFA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
