#pvc-ce7819a5-62a6-4697-ad25-dbdc5f1362c1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: default
spec:
  storageClassName: smb-reduced-retain #smb-retain
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
