---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-pv
  namespace: monitoring
spec:
  storageClassName: longhorn
  # by default, the volume will be not deleted if you delete the PVC, change to
  # "Delete" if you wish the volume to be deleted automatically with the PVC
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: prometheus
