apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:J7U4Gc0BGnCM5YwAzRA2MiQdJ/F61Yw6wU1MsTrhpdIg/9elt8PrqMYkeQlpB7hD8yRezNiZyYDTZi1G,iv:i4CkkPXzb8O0l+kt+fm3G7hKRTbuQNoW3LzFysrYG5I=,tag:WZc7fY49gfpEUXRHIBygLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOThveFNNUVZ5RERQclNE
            S0VtcGl6ZVhNa0RjbGlEUkw4QWt4YkVSbXdvClFrK1JQWkdqWUNxSWNPUW5iaWJo
            SDMyWitVOW4vUk9CSG9XTlg1dzNCUWsKLS0tIExVN1N4OTd1TVBleWZZcmNvMDZI
            QWw2aUpsa2ZQalBOVUhaSUpaZk00RTAKT8P2+fOgwWT4iJFA27D+a6gvqd7k7t/K
            PUX2jjzeENDFl/vTWSRMosn8HkasIIm71QoXGoaxAqiIpRDEkkqtqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-22T15:40:27Z"
    mac: ENC[AES256_GCM,data:IflVnv9G112zlSW+kEbu4BgG3Twg6/z3O/4ZntFnPE61JOcwNCKmfWIH5X4m1A1dHsHtw9u10AajyTz3bwDb7HyPM0P3K7V3O2CVvG/LB1fm9BdSNcJz08/51D4jmUmVlU871+uY4NtmT7fr7WvD2wsPGkqIxtJvkx6EU+ro/xQ=,iv:V3pwTrnp+Tuz2s32a8usFjy0dCsqFGP7nxI3I3NpB7M=,tag:fy+7D1EseWV38ZMaXf+UwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
