apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:f+AWi8L48IaQ7ikOVGJP7RFAupzo3v36VY1LYEYvVOZPAkSR7bfFVmyPJksVJwDAENUWPqcNwsLMJP7K,iv:ujh6DyAQIE7MJQ4D/aCDy1wZxwcWYiqOayJI4PwlLjI=,tag:nD6jtUdk3nxcUEhYJRGnMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjLy9TajFWWWQvcGFkeFlW
            bEt0bUZpckVvNVFoeHFHcTRETDlCeHpJSmlzCldqRlFYbDV2WTNzRlNUTDYyKzd6
            dk40MGg4OXUzWEVGZndQMEFoTFVXdTAKLS0tIGZDbmFDbWxLT2lsRFZ1OTZ3NkM2
            b0l4eEh4dTBaZlBQdENxekNkTG9nVm8KomoEaE/lAe6fAK2X7kbt0LeR6sv30INJ
            SmUgHglJJAe2kAza5dipmOVnXCIpPYX4kotNuDoskS+waBXBySseAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T08:02:43Z"
    mac: ENC[AES256_GCM,data:zEq6iFv1NhDBAxWegiCMfZ2yojHyrSxjXa8yHRVFojcdiC+V2ai+pQk8ahhT29oxX4Ice4eOR0VyCR3kwcpWNa00w1sao50JfDWfNQxkK5EEpAReQJPPjruPqoMRxihhiKyizBaaEtTfqvlJQq6oGo1pIYc16/fUJYiPVI47c9o=,iv:mJB6sHn4aTcarJ984Kd6tY4tobvSPyE3U4lo4HtS+hc=,tag:8a3qyRUItv9kpBIhs43c7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
