apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:QpbHTgUT2Mi4FypRBYf5iHTPxYXHVxT1n4c2OZPl/JEXsoqUW/IwsYEMeag19GF6AtuEgWhmzNhcnr6c,iv:NfyikRm8rCtAxeC/i7ohQpgxj2IfHA+02XtIy6wolq0=,tag:ueIbDglPKnm+oSPFQkIbhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeGh1TGtmblE0eW1QV1Fs
            NWRpeXBZZEMrNm92UDRZbW1NRy9Cd1RCZmdBCmhib1ppeEwxdldJVklham5adHNX
            ZUtqZTVpNFNaVzM2QzhNS2JTaWt2M0UKLS0tIG1RSHMwT0F5OGxjaCs5Ui9zVHJv
            QmxkMVFCWlBDSUcycnRCL0x6akJvT0kK3wHjNaKABgjs54hNpuWzM9WXozRs23Q6
            ET4ipdUQskhirBpkeno175ljikSJS7s7ybWFDRMEf1z+7+QUXTP7VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T20:24:12Z"
    mac: ENC[AES256_GCM,data:pNwhlNMZ8R3OD9zuuXlvAJ8gCHKKWZ2gohvx5OnzKgpPcwxXdqAUuWRsV3nLg92lTVHIuKyKXrlCPeb+cDI2zLrmssUNlVhXQ9fRGKgHwmO3ZYbz6KAiPwB8LHxliOeSqVFJk15szS73PisYHWKgpoShFMwJe4LRWWjrt9oD9Z4=,iv:190m9A0DELbFt1mbpWEhPrjCNH4t12ocaj2zGThLJYY=,tag:ibsBGZqxsdiv0XIaI24UEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
