apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:jDkaxeP79v+ktKS6O04IEMLdwtSfCODJQmcSuh+Nk8A0p0F5KXs9eh100Gxb801cTB+mKaKJDsqC5Rkp,iv:HsVrbnV8JkERRMbXyJRud3TRt5t0KiGUwv13kCha5Vw=,tag:jB2L/zsZ9fLEyzzB9DblbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MW1mQzg0UndlbGdvMTEx
            Y25OM0ovdHMxMGRqUldudmFqREFUaWJML0RnCmk2Zmt1MGMrL1l3ZjhSQ2EyNk9p
            K3FsY25PWTdpcmFFRGVOLzdpM3ovZVkKLS0tIEp2SjYxM0FsaWtHZVlZeXVzdHJ4
            dTB4ZWgyUy9Rd2ExMFFuWUhwOTNzRjAK8Kd5yRdF0ywtkuKDdW2CYR+Y3WxKQEXH
            aIn2nZ/mvNBZptqE4ds3XUKkHxEcWTQ8BpFznqoTxvAjddfCfcvhpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-17T14:46:28Z"
    mac: ENC[AES256_GCM,data:32JqpdEpz5fzlKL0ZZfR9D9ce6mytcucWoBBumS9u+ira5CX5+Sd/+J965LF7l3Ta/g5HgwBXJLKkdPhRdHjMzRmOuBO7sioRr2LTFLUxIZfvNpuN+mZzZnI1hNF4wBsGKYb36zF5YBFezOer8EJa1jZxvIk5z0mAKXZrNlfU4E=,iv:Sw6QvXg6NfDkZqAghMZjKC0Cx8syTvy7d4X3ckKU5C4=,tag:a27NmYqGuIuIdSxUa1v6Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
