apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:VBl3qtLAWCqeKSbe,iv:cpOd49ETa6NclIA/NvCKCshF/N/2R9Q0qqdyS4BMm9k=,tag:nHKy7pjL4lnOQ6xJ1Oc58A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:QW0jEEgOLDaS6EAS137nqMYOAcZAIpQmWM8=,iv:3dqx+v4oXQ3jVHf/5hwc940S3Unpx1nSFNcyceogVoU=,tag:mpec78idlgjWafc4/UQU0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p5stz83fpyrey8h89n7fs0p2us9pgv7gdtjt7legsgckyqfh5fdszqlnah
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndXdhdnR6d2xZdG83Z3JY
            QXVIeHhhVnQrY0MxZXhJN21FakVGVWtwSENrCml5a09VcjlKUTBRWXVHWmRGQ0h5
            WEhxZUFCRUhoQ0hMc2NCQStsVnJvbUEKLS0tIEVlcE1QSGFMTzV1WXM5NTRzZ3Yv
            TWxXY0RZVTBvRTROK2NQOXpNWXk1dUkK1xOAv/BvZKiJIY8RnTGkxixlsRaq289J
            XkLkErKYWouqY/TAKJXNNX/j5A94XiwCXKTN1WZdFGu1GFDUQZNiYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T08:02:43Z"
    mac: ENC[AES256_GCM,data:URwYOsaH3U/fttvpazpk67snJutb3Wm4R3HNRDpqoV+X6YDlMzGAb7wFqv9A8tkG0ENmwTcx8XenCMqdHDLRAd7C1vkAAu/8HdsPj3Mm63wFFbHuuKEfo0hNCm6jNvQq4TKoNV0Vw7vKbvlvxf7BDMxCT5dOP63EcsG9fpWE/Nc=,iv:96E82RxOSsdi8BrGK5ZIsW6mTlpnHRkUOcDBKWVJoko=,tag:yBzP6mnt4K7zqDgtRZElKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
