apiVersion: v1
kind: Pod
metadata:
  name: wget
  namespace: default
spec:
  containers:
    - name: wget
      image: mwendler/wget
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
