---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: postgres
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: default
spec:
  serviceName: postgres
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # initContainers:
      #   - name: init
      #     image: alpine
      #     command: ["sh", "-c", "chown 1001:1001 /var/lib/postgresql/data"]
      #     volumeMounts:
      #       - mountPath: /var/lib/postgresql/data
      #         name: postgres-persistent-storage
      containers:
        - image: postgres
          name: postgres
          securityContext:
            runAsUser: 1001
          env:
            - name: POSTGRES_USER
              # value: postgres
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: USERNAME
            - name: POSTGRES_PASSWORD
              # value: postgres
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: PASSWORD
      ports:
        - containerPort: 5432
          name: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
      volumes:
        - name: postgres-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
