---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ping-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9427"
    spec:
      containers:
        - image: czerwonk/ping_exporter
          imagePullPolicy: Always
          name: ping-exporter
          volumeMounts:
            - mountPath: /config/config.yml
              name: config-volume
              subPath: config
      volumes:
        - name: config-volume
          configMap:
            name: ping-exporter-conf
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ping-exporter-conf
  namespace: metrics
data:
  config: |
    targets:
      - 8.8.8.8
      - 8.8.4.4
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844
      - google.com

    dns:
      refresh: 2m15s
      nameserver: 1.1.1.1

    ping:
      interval: 2s
      timeout: 3s
      history-size: 42
      payload-size: 120
