---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  ports:
    - protocol: TCP
      port: 9798
      targetPort: 9798
  selector:
    app: speedtest-exporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: speedtest-exporter
      annotations:
        # prometheus.io/scrape: "true"
        # prometheus.io/path: /metrics
        # prometheus.io/port: "9798"
    spec:
      containers:
      # - args:
      #   - --config.path /config
      #   command:
      #   - /bin/unifi_exporter
        - image: miguelndecarvalho/speedtest-exporter
          imagePullPolicy: Always
          name: speedtest-exporter
          volumeMounts:
            - mountPath: /config/config.yml
              name: config-volume
              subPath: config
      volumes:
        - name: config-volume
          configMap:
            name: speedtest-exporter-conf
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-exporter-conf
  namespace: monitoring
data:
  config: |
    when in need
