---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: mosquitto
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket-nodeport
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 1883
      nodePort: 31883
  selector:
    app: mosquitto
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket-nodeport-2
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 1883
      nodePort: 30880
  selector:
    app: mosquitto
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: default
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:2.0.15
          # ports:
          # - containerPort: 80
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /mosquitto/data
              name: mosquitto-volume
            - mountPath: /mosquitto/config
              name: config
      volumes:
        - name: mosquitto-volume
          persistentVolumeClaim:
            claimName: mosquitto-pvc
        - name: config
          configMap:
            name: mosquitto-conf
              # resources:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-conf
  namespace: default
data:
  mosquitto.conf: |
    log_dest stdout
    listener 1883
    listener 9090
    protocol websockets
    allow_anonymous false
    password_file /mosquitto/data/j-burg11-mosquitto-passwd
---
#pvc-32d4802d-e7ed-4306-a750-b890d3982222
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
