apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: mosquitto-mosquitto
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket-nodeport
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 1883
      nodePort: 31883
  selector:
    app: mosquitto-mosquitto
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-websocket-nodeport-2
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 1883
      nodePort: 30880
  selector:
    app: mosquitto-mosquitto
  type: NodePort
